service:
    commands:
        producer:
            bootstrap-server: localhost:9092
            topic: pet-commands
            client-id: pet_commands_producer
            ack: all
            timeout-ms: 500
