spring:
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/postgres
        username: user
        password: pass
service:
    commands:
        consumer:
            bootstrap-server: localhost:9092
            topic: pet-commands
            client-id: pet_commands_consumer
            group-id: pet_commands_consumers
            offset-earliest: earliest
            timeout-ms: 500
            retries:
                times: 5
                ms: 300000

db:
    initialize: false
